# Exported from Render on 2024-07-22T12:42:39Z
services:
- type: web
  name: Ex04RenderAPI-1
  runtime: node
  repo: https://github.com/AtheerAzaizeh/Ex04RenderAPI
  plan: free
  envVars:
  - key: DB_PASSWORD
    sync: false
  - key: DB_NAME
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_HOST
    sync: false
  - key: PORT
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: node server.js
- type: web
  name: Ex04RenderAPI
  runtime: node
  repo: https://github.com/AtheerAzaizeh/Ex04RenderAPI
  plan: free
  envVars:
  - key: DB_PASSWORD
    sync: false
  - key: DB_NAME
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_HOST
    sync: false
  - key: PORT
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: npm start
version: "1"
